"""
Column names in dataframes
"""

ACCOUNT_TYPE = 'account_type'
ACCOUNT_GUID = 'account_guid'
POST_DATE = 'post_date'
ENTER_DATE = 'enter_date'
FULLNAME = 'fullname'
SHORTNAME = 'name'
TRANSACTION_GUID = 'transaction_guid'
NOTES = 'notes'
XIRR_ENABLE = 'xirr_enable'
XIRR_ACCOUNT = 'xirr_account'
XIRR_VALUE = 'xirr_value'
GUID = 'guid'
QUANTITY = 'quantity'
VALUE_CURRENCY = 'value_currency'
HIDDEN = 'hidden'
CUM_SUM = 'cum_sum'
VALUE = 'value'
COMMODITY_GUID = 'commodity_guid'
MNEMONIC = 'mnemonic'
NAMESPACE = 'namespace'
CURRENCY_GUID = 'currency_guid'
RATE = 'rate'
RATE_CURRENCY = 'rate_currency'
DESCRIPTION = 'description'
YIELD_TOTAL = 'yield total'
YIELD_INCOME = 'yield_income'
YIELD_EXPENSE = 'yield_expense'
YIELD_CAPITAL = 'yield_capital'
PARENT_GUID = 'parent_guid'
PRICE_CURRENCY_GUID = 'price_currency_guid'
START_DATE = 'start_date'
END_DATE = 'end_date'
DAYS = 'days'
